name: Publish to NPM registry

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type - major, minor or patch'
        required: true
        default: 'patch'
      distTag:
        description: 'NPM tag (e.g. use "next" to release a test version)'
        required: true
        default: 'latest'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      # Auth for npm
      - run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Optional: set your desired author for release commits
      - name: Git Setup
        run: |
          git config user.name "Sam Treweek"
          git config user.email "samtreweek@gmail.com"  

      - run: npm ci

      # Install Playwright browsers & OS deps (no CDN dance in your YAML)
      - uses: microsoft/playwright-github-action@v1

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Run eslint & prettier
        run: npm run lint && npm run format:check

      - name: Run tests
        run: npx playwright test

      - name: Release
        run: npm run release:ci -- ${{ github.event.inputs.releaseType }} --npm.tag=${{ github.event.inputs.distTag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}